### ISSUE TITLE
팀 프로젝트 주제 선정 필요

### ISSUE THREAD

**Issue by minyoung10** [MiniProject-Team9/Project#2]
예시) 
CAFE 디저트 자판기
출퇴근 관리 시스템
스터디 카페! 이젠 어디서든 예약할 수 있어요
가계부 프로그램

**Comment by minyoung10** [comment]
개인 프로젝트 진행 시 축구 구단 경기 정보 관리시스템을 구현했었습니다.

**Comment by poly0112** [comment]
개인 프로젝트 때 도서관 대출 관리 프로그램 구현했었습니다.

**Comment by minyoung10** [comment]
제것보다 도서관 주제가 더 확장성이 좋다고 생각합니다.

**Comment by poly0112** [comment]
그럼 도서관 대출 관리 프로그램을 기반으로 더 확장해서 프로젝트를 만들어 볼까요?

**Comment by minyoung10** [comment]
아니면 추가적으로 주제를 더 생각해본 후 논의 해봐요!

**Comment by minyoung10** [comment]
푸드코트, 강의실 대여 시스템,  음식점 티켓 자판기

**Comment by minyoung10** [comment]
https://github.com/TeamProject-2022OSS/miniProject#%EA%B9%80%EC%98%88%EC%84%B1-y-eseong-github-link
교수님께서 예시로 주신 자판기 시스템인데, 이것을 응용하여 음식점(명성) 키오스크 관리 시스템을 구현하는 것도 좋을꺼 같습니다.

**Comment by poly0112** [comment]
그럼 음식점 키오스크 관리시스템을 주제로 선정합시다
