### ISSUE TITLE
음식점 키오스크 시스템 기능구현 논의 필요

### ISSUE THREAD

**Issue by minyoung10** [MiniProject-Team9/Project#3]

**Comment by minyoung10** [comment]
CRUD 기능, 데이터 파일 저장/읽어오기, 검색 메뉴 를 기본으로 설정하고
추가사항 입력 메뉴와 같은 새로운 기능을 구현이 필요합니다.

**Comment by poly0112** [comment]
일정 가격 이하의 메뉴를 검색 하는 기능을 하나 추가합시다

**Comment by poly0112** [comment]
일정 가격 이상의 메뉴를 검색하는 기능과 기본 맵기를 0으로 해놓고 맵기 기능을 3단계까지 표현하는 기능을 넣으면 좋을 것 같아요

**Comment by minyoung10** [comment]
클로즈 하고 추후 개발 시 새로운 이슈 생성하여 심도있게 진행하겠습니다.
