### ISSUE TITLE
팀소개 및 팀원이 맡은 역할

### ISSUE THREAD

**Issue by poly0112** [MiniProject-Team9/Project#4]
각자의 역할분담이 필요할 것 같습니다.

**Comment by poly0112** [comment]
저는 CRUD 구현과 부가기능 구현을 위주로 하고 싶습니다.

**Comment by minyoung10** [comment]
저는 Repo Owner, 부가기능구현,
WIKI 관리, 코드 관리 (오류수정), 로고제작
등 github 페이지 관리를 중점으로 하고싶습니다.
