### ISSUE TITLE
추가 기능 관련 논의

### ISSUE THREAD

**Issue by minyoung10** [MiniProject-Team9/Project#8]
특정 가격 이상의 메뉴 보여주는 기능은 주문서에서 그 가격보다 높은 항목(음식)들을 삭제하는 것인가요?

**Comment by minyoung10** [comment]
음식 종류별로 조회가능한 기능 추가하면 좋을꺼 같습니다.

**Comment by poly0112** [comment]
맵기 단계 기능 추가 하고 특정가격 이상 보여주는 기능은 삭제하저

**Comment by minyoung10** [comment]
네 좋습니다. 그러면 해당 기능은 제가 구현하도록 하겠습니다.
